---
DISCORD_TOKEN: 'SOMESUPERLONGSTRINGOFLETTERSANDMAYBENUMBERS' # Discord API key for bot created in developer portal.
CALLSIGN_CHANNEL_ID: 123456789101112 # Channel ID of dedicated channel for bot to listen for callsigns.
GENERAL_CHANNEL_ID: 123456789101112 # Channel ID of general discussion channel or anywhere you want new callsigns to be announced when people join.
LOGGING_CHANNEL_ID: 123456789101112 # Channel ID for bot logging to be send (Note: this should probably be a muted channel).
CLUB_CALL: 'W8FY'